line-length = 110
target-version = "py311"
extend-exclude = [
  "app/db/migrations",
]

[lint]
select = [
  "E", "F", "W",   # pycodestyle/pyflakes
  "I",            # isort
  "UP",           # pyupgrade
 "B",            # flake8-bugbear
]
ignore = [
  "E501",  # line length handled pragmatically
]

[lint.per-file-ignores]
"tests/**" = ["B018", "S101"]
"app/db/migrations/**" = ["D", "E", "F", "I", "UP", "B", "RUF"]
"app/bot/handlers.py" = ["F841", "RUF001", "RUF003", "RUF005", "SIM103", "SIM105", "SIM108"]

